### ISSUE TITLE
Error downloading https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json

### ISSUE THREAD

**Issue by Phr3d13** [stm32duino/BoardManagerFiles#15] opened 2018-11-30 21:10 UTC
Issue is the title, link does not resolve inside arduino.ide, but appears to work when linked in normal browsing.

**Comment by fpistm** [comment] 2018-11-30 22:33
Seems to be a proxy issue. Please check Arduino proxy config

**Comment by Phr3d13** [comment] 2018-12-01 00:13
Fails for me with auto and no proxy (both should work for me, as I can click the link and view it in my web browser and it doesn't use any proxies).
Update: fails with my copy of 1.8.7 downloaded from the internet, but works with my copy from the windows app store

**Comment by fpistm** [comment] 2018-12-01 06:00
Ok. Unfortunately, I will not able to help. It is an issue with Arduino IDE.
You could submit an issue on Arduino GitHub.

**Comment by fpistm** [comment] 2018-12-01 06:19
Maybe the same issue to this one:
https://github.com/arduino/Arduino/issues/7982

**Comment by sige1** [comment] 2018-12-13 14:27
This error is not it?

Skipping contributed index file /Users/.../Library/Arduino15/package_stm_index.json, parsing error occured:
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.FileInputStream@813c758; line: 7, column: 2]

Arduino Preferences
Additional Borads Manager URLs:
https://github.com/stm32duino/BoardManagerFiles/blob/master/STM32/package_stm_index.json
 ↓
https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json

After change URL, I confirmed that it works correctly.

**Comment by fpistm** [comment] 2018-12-17 07:36
Referring to the Title, @Phr3d13 use the right URL.
https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json

**Comment by fpistm** [comment] 2019-02-11 09:54
Close it as not linked to specific stm32duino issue.

**Closed as completed by fpistm** 2019-02-11 09:54 UTC

**Comment by pasindu-sandima** [comment] 2019-09-03 13:51
I had the same issue and I fixed it doing the following steps.

1. Open Arduino IDE
2. Go to preferences
3. Click on the link to edit preferences.txt ( This will take you to `C:\Users\$Username\AppData\Local\Arduino15`)
4. Delete the temp file and the json file from that directory
5. Delete the package in the packages folder
6. Delete staging files related to that in the staging folder
7. Restart the device and add the link again and try

![image](https://user-images.githubusercontent.com/37769828/64178896-dcacee80-ce7f-11e9-9748-9a69db1531b8.png)
![image](https://user-images.githubusercontent.com/37769828/64178933-ecc4ce00-ce7f-11e9-8099-9401a536d981.png)
![image](https://user-images.githubusercontent.com/37769828/64178981-fcdcad80-ce7f-11e9-9587-cc19f8b4849a.png)
