### ISSUE TITLE
Using Arduino IDE on Raspberry

### ISSUE THREAD

**Issue by JimKnopf1503** [stm32duino/BoardManagerFiles#39] opened 2022-04-04 13:21 UTC
Hi!
In the last weeks I used the IDE on my windows computer. Now I like to use it on my raspberry.
I added https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json under preferences.
But when I try to install STM32 MCU based board, I got "Werkzeug STM32Tools ist für Ihr Betriebssystem nicht verfügbar", that means STM32Tools ist not available for my OS.
Is there a way to compile it for ARM-Linux?

Thanks,
Burkhard

**Comment by fpistm** [comment] 2022-04-04 13:53
Hi, currently ARM support is not provided.
An issue is already open for this on the core:
https://github.com/stm32duino/Arduino_Core_STM32/issues/708

in the thread you will see that user have made it to work:
https://github.com/koendv/stm32duino-raspberrypi

I close this one as it is a duplicate of https://github.com/stm32duino/Arduino_Core_STM32/issues/708

**Closed as completed by fpistm** 2022-04-04 13:53 UTC
Labels: duplicate
