### ISSUE TITLE
Error in compiling the code in arduino ide for stm32f103 board, a big thanks if anyone can help

### ISSUE THREAD

**Issue by hakam007** [stm32duino/BoardManagerFiles#48] opened 2022-09-29 01:22 UTC
hello sir , i am facing a error problem since more than a month in arduino IDE ,i am using stm32f103 board, error is as given below:

arm-none-eabi-g++: error: Singh\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.3.0=.: No such file or directory
exit status 1
Error compiling for board Generic STM32F1 series........

Then i puchased a new board stm32f401 board ,then also found same error ... i really dont know what i can do ,kindly help me in this it will be a really a great help... thanks
![error pic1](https://user-images.githubusercontent.com/113838334/192917224-a7b8c9ea-b466-4f5e-8c2c-171a98051f52.png)

**Comment by fpistm** [comment] 2022-09-29 04:56
Hi, it is already know and fixed thanks https://github.com/stm32duino/Arduino_Core_STM32/pull/1759

Fix will be available in the 2.40 release.
Simply replace C:\Users\<your username>\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.3.0\system\extras\prebuild.sh by this file while 2.4.0 is not released:
https://github.com/stm32duino/Arduino_Core_STM32/blob/main/system/extras/prebuild.sh

Duplicate of 
https://github.com/stm32duino/Arduino_Core_STM32/issues/1829

**Closed as completed** 2022-09-29 04:56 UTC
Labels: duplicate

**Comment by hakam007** [comment] 2022-09-29 12:43
@fpistm  oh my God  you are such a genuis person ,really no words to thankyou...you proved saviour for me.. may god bless you

**Comment by fpistm** [comment] 2022-09-29 15:09
> @fpistm oh my God you are such a genuis person ,really no words to thankyou...you proved saviour for me.. may god bless you

Not so genius as it's me who introduced the regression :wink:

**Comment by hakam007** [comment] 2022-09-29 17:20
woww so nice.. i am feeling like m talking to a great person

**Comment by hakam007** [comment] 2022-09-30 07:53
@fpistm  Hii sir , i am facing problem in uploading code in stm32f103c8t6 , uploading error occured.  plz guide me in this
![blue pill blink](https://user-images.githubusercontent.com/113838334/193220166-bd775014-2b19-4959-98cd-725f7a5e8866.png)

**Comment by fpistm** [comment] 2022-09-30 08:11
Hi @hakam007 

please use the forum for such support: http://www.stm32duino.com
